### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined when signing maker order

### ISSUE THREAD

**Issue by najienka** [LooksRare/looksrare-sdk#32]
**Describe the bug**
Getting an array length error during Abi encoding when calling the `signMakerOrder()` function in the SDK to purchase an NFT listed on the Rinkeby testnet (any real world example JS script of a Rinkeby testnet purchase using the SDK will be appreciated).

```
An unexpected error occurred:

TypeError: Cannot read property 'length' of undefined
    at AbiCoder.encode (/Users/nemitariajienka/Desktop/projects/heni-nftmarket-contract/node_modules/@ethersproject/abi/src.ts/abi-coder.ts:101:19)
    at /Users/nemitariajienka/Desktop/projects/heni-nftmarket-contract/node_modules/@looksrare/sdk/dist/index.cjs.js:7191:46
    at Generator.next (<anonymous>)
    at fulfilled (/Users/nemitariajienka/Desktop/projects/heni-nftmarket-contract/node_modules/@looksrare/sdk/dist/index.cjs.js:7086:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**To Reproduce**

Create a makerOrder to purchase any NFT listed on the LooksRare Rinkeby testnet, e.g., https://rinkeby.looksrare.org/collections/0xd4C4643053E46eacffa06E2573641907a54125Fb/12 

Either add or do not add the `asset price in Wei` within the paramsValue array and specify the type in the paramsTypes array as `['uint']`.

The order used is as follows:

```
const makerOrder = {
    // true --> ask / false --> bid
    isOrderAsk: false,
    // signer address of the maker order
    signer: signers[0].address,
    // collection address
    collection: '0xd4C4643053E46eacffa06E2573641907a54125Fb',
    // Price in WEI
    price: ethers.utils.parseEther('0.0001'),
    // Token ID
    tokenId: 12,
    // amount of tokens to sell/purchase (must be 1 for ERC721, 1+ for ERC1155)
    amount: 1,
    // strategy for trade execution (e.g., DutchAuction, StandardSaleForFixedPrice), see addresses in the SDK
    strategy: '0x732319A3590E4fA838C111826f9584a9A2fDEa1a',
    // currency address
    currency: '0xc778417E063141139Fce010982780140Aa0cD5Ab', // should be eth
    // order nonce (must be unique unless new maker order is meant to override existing one e.g., lower ask price)
    nonce: 678,
    // startTime timestamp in seconds
    startTime: Date.now(),
    // endTime timestamp in seconds
    endTime: (Date.now()) + 604800,
    // minimum ratio to be received by the user (per 10000)
    minPercentageToAsk: 0, // BigNumber.from(10000).sub(protocolFees.add(creatorFees)).toNumber(),
    // params (e.g., price, target account for private sale)
    params: paramsValue,
  };

```
**Expected behavior**
The order should be signed and broadcasted on chain with a successful purchase and transfer of ownership of the listed NFT to the buyer address.

**Additional context**
None.

**Comment by 0xShisui** [comment]
Need more information about the code you use to sign and create the contract instance

**Comment by najienka** [comment]
This is the code used to sign the order. It's imported from the SDK
const { signMakerOrder } = require("@looksrare/sdk");

const signatureHash = await signMakerOrder(signers[0], SupportedChainId.RINKEBY, makerOrder, ['uint']);

Is there any sample working code used to purchase an item from LooksRare using the SDK?

**Comment by 0xShisui** [comment]
> This is the code used to sign the order. It's imported from the SDK `const { signMakerOrder } = require("@looksrare/sdk");`
> 
> `const signatureHash = await signMakerOrder(signers[0], SupportedChainId.RINKEBY, makerOrder, ['uint']);`
> 
> Is there any sample working code used to purchase an item from LooksRare using the SDK?

- Unless you are doing a private sale, you params should just be an empty array 
- You sign function is missing a param : https://github.com/LooksRare/looksrare-sdk/blob/master/src/sign/makerOrder.ts#L63

**Comment by 0xShisui** [comment]
Here is how we used it:

```ts
interface PostMakerOrderOptionalParams {
  tokenId?: string;
  startTime?: number;
  endTime?: number;
  params?: { values: any[]; types: SolidityType[] };
}

/**
 * Create a maker order and returns it 
 * @param signer Etherjs signer
 * @param signerAddress Address that signed the message
 * @param chainId Current chaind id
 * @param isOrderAsk Is it an ask or bid order
 * @param collectionAddress Collection address
 * @param strategyAddress Address of the strategy used
 * @param amount Number of tokens to buy
 * @param price Price in wei
 * @param protocolFees Protocol fees
 * @param creatorFees Collection fees
 * @param currency Currency address
 * @param optionalParams Optional parameters
 * @param optionalParams.tokenId Token id (default to 0 for collection orders)
 * @param optionalParams.startTime Sale start time (default to now)
 * @param optionalParams.endTime Sale end time (default to now + 6 months)
 * @param optionalParams.params If you wonder what to user here, then use empty array []
 * @returns MakerOrderWithSignature The maker order
 */
const prepareMakerOrder = async (
  signer: ethers.providers.JsonRpcSigner,
  signerAddress: string,
  chainId: number,
  isOrderAsk: boolean,
  collectionAddress: string,
  strategyAddress: string,
  amount: BigNumber,
  price: BigNumber,
  nonce: BigNumber,
  protocolFees: BigNumber,
  creatorFees: BigNumber,
  currency: string,
  optionalParams: PostMakerOrderOptionalParams = {}
) => {
  const now = Date.now();
  const { tokenId, params, startTime, endTime } = optionalParams;
  const paramsValue = params ? params.values : [];
  const paramsTypes = params ? params.types : [];
  const netPriceRatio = BigNumber.from(10000).sub(protocolFees.add(creatorFees)).toNumber();

  const makerOrder: MakerOrder = {
    isOrderAsk,
    signer: signerAddress,
    collection: collectionAddress,
    price: price.toString(),
    tokenId: tokenId?.toString() || "0",
    amount: amount.toString(),
    strategy: strategyAddress,
    currency,
    nonce: nonce.toNumber(),
    startTime: startTime ? Math.floor(startTime / 1000) : Math.floor(now / 1000),
    endTime: endTime ? Math.floor(endTime / 1000) : Math.floor(addTime(now, { months: 1 }).getTime() / 1000),
    minPercentageToAsk: Math.min(netPriceRatio, minNetPriceRatio),
    params: paramsValue,
  };
  const signatureHash = await signMakerOrder(signer, chainId, addresses.EXCHANGE, makerOrder, paramsTypes);

  const data: MakerOrderWithSignature = {
    ...makerOrder,
    signature: signatureHash,
  };

  return data;
};
```

**Comment by 0xShisui** [comment]
I don't see any activity so I'll close this issue. If you still have any problem, let me know.
